version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    # hostname: "localhost"
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - rabbitmq
    restart: unless-stopped

  order:
    image: ${DOCKER_REGISTRY-}order
    depends_on:
       - rabbitmq
       - initiator
    build:
      context: .
      dockerfile: Order/Dockerfile
  payment:
    image: ${DOCKER_REGISTRY-}payment
    depends_on:
       - rabbitmq
       - initiator
    build:
      context: .
      dockerfile: Payment/Dockerfile
  invoice:
    image: ${DOCKER_REGISTRY-}invoice
    depends_on:
       - rabbitmq
       - initiator
    build:
      context: .
      dockerfile: Invoice/Dockerfile
  initiator:
    image: ${DOCKER_REGISTRY-}initiator
    depends_on:
       - rabbitmq
    build:
      context: .
      dockerfile: Initiator/Dockerfile
networks:
  rabbitmq:
    driver: bridge